# 公共配置文件

spring:
  application:
    name: backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/niuniu
    username: root
    password: 123456
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis #表示从redis读写session
  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印sql语句
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#接口文档访问路径：http://localhost:8080/api/doc.html
# Knife4j文档
knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: admin
  openapi:
    title: 接口文档
    description: "伙伴匹配系统接口文档"
    # aaa"
    email: xiaoymin@foxmail.com
    concat: xxx
    url: https://www.xxxx.com/
    version: v4.0
    license: Apache 2.0
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.fbs.partnermatch.controller